**TASK:** import numpy

In [49]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [50]:
x = np.array([1,2,3])

**TASK:** define (2 x 2) matrix 'A' 


In [51]:
A = np.array([[1,1],[2,2]])

**TASK:** define (2 x 2) matrix 'B'

In [52]:
B = np.array([[3,2],[5,6]])

**TASK:** check the type of 'x'

In [53]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [54]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [55]:
np.shape(A)

(2, 2)

**TASK:** check the type of 'A'

In [56]:
type(A)

numpy.ndarray

**TASK:** 

In [57]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

"\nDefine function 'have_same_shape' which checks if two arrays have same shape.\n\nPARAMS:\n    array_1 (numpy.ndarray) - first array\n    array_2 (numpy.ndarray) - second array\nRETURN:\n    True - if arrays have same shape\n    False - if arrays do not have same shape\n\nAlso print 'Arrays must have same shape!' when returning False\n"

In [58]:
def have_same_shape(array_1,array_2):
    return np.shape(array_1) == np.shape(array_2)

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [59]:
have_same_shape(A,x)

False

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [60]:
have_same_shape(A,B)

True

**TASK:** 

In [61]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


"\nDefine function 'matrix_addition' which perform matrix addition value by value.\n\nPARAMS:\n    A (numpy.ndarray) - first array\n    B (numpy.ndarray) - second array\nRETURN:\n    C (numpy.ndarray) - new A+B array\n\nIn this task do not consider broadcasting.\nDo not forget to check arrays shapes (you can use 'have_same_shape' function defined before)\n\n"

In [62]:
def matrix_addition(A,B):
    return A+B

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [63]:
matrix_addition(A,B)

array([[4, 3],
       [7, 8]])

**TASK:** 

In [64]:
"""
Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [69]:
def multiple_matrix_addition(lst_ofarr):
    
    # initialize matrix with zeros
    matrix_sum = np.zeros((2,2), dtype = "int16")
    
    #loop through the matrix
    for val in lst_ofarr:
        
        # check if the shapes are the same.
        if not have_same_shape(val, matrix_sum):
            print("Can not add matrix with different shape!")
            return
        
        # add matrix
        matrix_sum = matrix_addition(val, matrix_sum)
        
    return matrix_sum

**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [70]:
multiple_matrix_addition([A,A,B,B])

array([[ 8,  6],
       [14, 16]])

**TASK:** 

In [67]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

"\nDefine function 'can_multiply' that checks if two arrays (matrices) can be multiplied\n\nPARAMS:\n   array_a (numpy.ndarray) - first array\n   array_b (numpy.ndarray) - second array\nRETURN:\n    True - if arrays can be multiplied, also print the shape of the new array\n    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'\n    \n"

In [114]:
def can_multiply(A, B):
    return np.shape(A)[1] == np.shape(B)[0]

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [115]:
can_multiply(A,B)

True

**TASK:**  define matrix (3 x 2) matrix C

In [116]:
C = np.ones((3,2))

**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [117]:
can_multiply(A,C)

False

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [118]:
can_multiply(C,A)

True

**TASK:** 

In [ ]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

In [119]:
def matrix_multiplication(A,B):
    
    # check if A and B can be multiplied
    if not can_multiply(A,B):
        print("Can not multipy!")
        return
    return np.dot(A,B)

**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [120]:
matrix_multiplication(C,B)

array([[8., 8.],
       [8., 8.],
       [8., 8.]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [121]:
matrix_multiplication(A,C)

Can not multipy!
